### PR TITLE
Some changes....

### PR DESCRIPTION
**Pull request by keflavich**
I don't think you should merge this.... it looks like there are some redundant files, etc.  However, I've made some important bugfixes.

### CODE REVIEW

**Comment by keflavich** [comment]
Well... this is really weird.  This branch is NOT identical to vlas-sokolov/redefined_fiteach... but it seems to think that it is?!

**Comment by keflavich** [comment]
ok, fixed it.  My git got into a really weird state because I had opened (but not run! or changed!) some ipython notebooks.

**Comment by vlas-sokolov** [comment]
Looks good. To be honest, I have no idea what to do with the whole redefining `fiteach` business - I think that hijacking the pyspeckit function was a very bad design philosophy and something I should not have pushed to public. I wrote the function as part of playing around with the original one (it has a neat option that allows the guesses to be more flexible and the error handling is somewhat different), but it's 
otherwise a dumbed down version of pyspeckit's fiteach.

Perhaps an option to proceed is to make `use_best_as_guess` available in pyspeckit? Not sure how useful that would be outside of multicube though.

**Comment by keflavich** [comment]
I think making `pyspeckit` more flexible is the best option.

Would it perhaps make more sense to have something like:
```
sp.fiteach(guesses=multicube_sp.best_guesses)
```
?  Or are there other parameters that are intrinsic to the multicube that need to be considered simultaneously?  If the latter, could you enumerate them?

It would be a good goal to remove fiteach from multicube and just have pyspeckit be able to handle multicube's outputs.

**Comment by vlas-sokolov** [comment]
This unorthodox tinkering of mine with pyspeckit's SpectralCubes is what was keeping me from merging this branch into master.

Yes, integrating the changes into pyspeckit's fiteach might be the best route to take - I'll see when I get around to make a compatibility PR to pyspeckit.

**Comment by vlas-sokolov** [comment]
> Or are there other parameters that are intrinsic to the multicube that need to be considered simultaneously? 
Forgot to explicitly say that no, no other major differences exist.

I'll merge this for now and will reverse the proper `fiteach` behavior in a different PR.

**Pull request merged**
